### ISSUE TITLE
400 bad request when I first sign in with my gmail

### ISSUE THREAD

**Issue by hihuaweizhu** [cansinacarer/My-Base-SaaS-Flask#1]
![Screenshot 2024-08-18 045109](https://github.com/user-attachments/assets/ae785ba3-f859-4356-ac37-cc8c2f6be73c)
Error 400:
https://base-saas-flask.apps.cansin.net/login/callback/google?code=4%2F0AcvDMrBF9Lc7LU4hbylUYK1ZyuLRzhQGwMKdSyWxyQayX4XDdgO_WD66NiufUVcob2cOyQ&scope=email+profile+openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&authuser=0&prompt=consent

**Comment by cansinacarer** [comment]
[Fixed](https://github.com/cansinacarer/my-base-saas-flask/pull/4/commits/4e83ecad478d92c0b11f6a9efd5b2e393a617241)
